name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      node-version: 16

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: touch key.json
    - run: npm run build --if-present
    - run: sudo timedatectl set-timezone Asia/Tokyo
    - run: npm test -- -t ${{ secrets.CODECOV_TOKEN }}
